export const API_BASE_URL = "/api";
export const API_AUTH_ATTEMPT = API_BASE_URL + "/users/login";
export const API_LOGOUT = API_BASE_URL + "/users/logout";
export const API_GET_USER = API_BASE_URL + "/users/get_user";
export const API_REGISTER = API_BASE_URL + "/users/register";
export const EVENT_AUTH_SUCCESS = "event_auth_success";
export const EVENT_AUTH_FAILED = "event_auth_failed";
export const ACTION_SET_USER = "action_set_user";
export const ACTION_SET_CITIES = "action_set_cities";